#!/bin/bash

# Descargar la clave GPG de Brave
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

# Agregar el repositorio de Brave al archivo de lista de fuentes
echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

# Actualizar la lista de paquetes
sudo apt update

# Instalar Brave Browser
sudo apt install brave-browser
